apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169637828
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169637828
    app.kubernetes.io/part-of: test-app-169637828
  name: go-169637828
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169637828
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169637828
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/xbd4iqkg-tenant/test-app-169637828/go-169637828@sha256:0a942a7034febea02071e12ca7e4047a7cf191ac0e72b9d95318308c02f04cf5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
